### ISSUE TITLE
Support Dark theme

### ISSUE THREAD

**Issue by vchirikov** [MrLuje/vs-commitizen#15]
Hi, thanks for your work, I want to suggest implement a dark theme support. Now your extension looks like this:
![default](https://user-images.githubusercontent.com/40987940/47189457-5fe75380-d345-11e8-972f-d29b0c5e40fa.png)

**Comment by MrLuje** [comment]
Hi, I'll have a look

Meanwhile, can you confirm which version of VS do you have ? It looks a bit better here
![image](https://user-images.githubusercontent.com/632075/47307856-5ead7380-d630-11e8-95a3-204a3d81d810.png)

**Comment by vchirikov** [comment]
VS 15.9.0 Preview 3.0

**Comment by MrLuje** [comment]
Please give the last release a try
