### ISSUE TITLE
Missed stash dropdown in VS 2019

### ISSUE THREAD

**Issue by vchirikov** [MrLuje/vs-commitizen#19]
**Describe the bug**
Without extension we have dropdown button to stash changes, like this:
![default](https://user-images.githubusercontent.com/40987940/53802914-2a3db280-3f54-11e9-8cda-da73288eed91.png), but your extension button hide this button.

**To Reproduce**
1. Go to Changes

**Expected behavior**
Dropdown with stash + vscommitizen button are visible.

**Visual Studio (please complete the following information):**
 - community
 - 2019

**Comment by MrLuje** [comment]
It was so properly hidden I didn't even notice... good catch
