### ISSUE TITLE
Fix footer of the commit message

### ISSUE THREAD

**Issue by vchirikov** [MrLuje/vs-commitizen#24]
Hi, @MrLuje 
According to https://www.conventionalcommits.org/en/v1.0.0/#specification

* Current "BREAKING CHANGES: " should be replaced by "BREAKING CHANGE: "
*  "Closes: "  editbox should add some of `token: ` now it just appends to footer. 
    >Each footer MUST consist of a word token, followed by either a `:<space>`)
* Add checkbox like "Does the commit contain breaking changes?" or auto add `!` to type. (?)

**Comment by MrLuje** [comment]
Hi, thanks for the remarks, I'll have a look
Is the v1 still the thing ? I can only find betas in english

**Comment by vchirikov** [comment]
Thanks!
