### ISSUE TITLE
Commitizen button is no longer visible

### ISSUE THREAD

**Issue by yannduran** [MrLuje/vs-commitizen#34]
In VS 2019 **v16.8.x**, the _Commitizen_ button no longer appears in the _new Git experience_'s **_Git Changes_** window.

![image](https://user-images.githubusercontent.com/2031126/104668569-73541580-572c-11eb-91c3-6edbc0fe7f31.png)

It's obviously Visual Studio that has broken the existing functionality with its new changes window. 

This means that if the _new Git experience_ is active, _Commitizen_ can no longer be used unless a way to incorporate it into the new _**Git Changes**_ window is found.

**Comment by charabaruk** [comment]
As of 16.9.4, Git Changes seems to be the default and so the Commitizen button is no longer accessible.

**Comment by MrLuje** [comment]
AFAIK, there is no built-in extensibility in the new git experience, so I don't think I can bring back the button for now.
Meanwhile, you can still access the existing panel through "Team Explorer" > VsCommitizen (yep, ugly... you will have both new & old git view at the same time...)

I'll probably make the Commitizen view a regular tab with a "copy commit message"... not as smooth as the button, but it will do the job

**Comment by yannduran** [comment]
@MrLuje I've abandoned the _new Git experience_ and have been using _Team Explorer_ so I can actually get some work done, instead of trying to find where what I'm looking for has been hidden away.

There are some great improvements in the individual new components, but it doesn't even come close to _Team Explorer_ in ease of use, discoverability and possibly (as you mentioned) extensibility. Everything's scattered all over the place, and what you to be a single click now involves more clicks.

Thanks for replying!
